# Author: George Quentin
sources:
- ./BreweryDBKit/Models
- ./BreweryDBKit/Services
templates:
- ./../Sourcery/Templates/AutoAPICollectionResponse.stencil
- ./../Sourcery/Templates/AutoAPIRequestQueryItems.stencil
- ./../Sourcery/Templates/AutoJSONDecodableAPIModel.stencil
output:
 ./BreweryDBKit/Generated
args:
